### ISSUE TITLE
Test-OktaNext Example?

### ISSUE THREAD

**Issue by sandpitt** [Seekatar/OktaPosh#17]
Is there any documentation available for now Test-OktaNext should be used? Have not been able to successfully check if there are more pages for Get-OktaApplicationUser when passing either "users" or "apps" in Test-OktaNext's ObjectName paramater.

**Comment by Seekatar** [comment]
Looks like that's a gap in OktaPosh.  Test-OktaNext works when getting the base item Get-OktaUser or Get-OktaApp, but currently doesn't do ApplicationUser.  I'll put that on the list.

This works, from about_oktaposh_paging.md

Get-OktaGroup -limit 10
while (Test-OktaNext groups) { Get-OktaGroup -next }

**Comment by JaredPittmanMyriad** [comment]
Makes sense, thought that might be the case. For the time being I've implemented a workaround in my code by catching the warning that gets triggered once the "-next" flag runs out of pages. Appreciate the quick response, thanks for providing such a useful repo!

Jared

**Comment by Seekatar** [comment]
0.2.7 supports Test-OktaNext for anything that has -Next.  Tab-completion will show what is valid and I updated the examples in about_oktaposh_paging.md. There's also -NoWarn to suppress the warning (which you could also do with `3>$null`)
